version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linkhub
    ports:
      - "3000:3000"
  nginx:
    image: nginx:alpin
    container_name: nginx-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:3000
    depends_on:
      - app
