# syntax=docker/dockerfile:1
FROM node:18-alpine
WORKDIR /app

RUN apk add --no-cache openssl dos2unix

COPY . /app
# RUN dos2unix /compose-entrypoint.sh

EXPOSE 3000
# ENTRYPOINT ["sh", "/compose-entrypoint.sh"]
